In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3])

In [ ]:
def compose(a):
  if a.shape[0]!=a.shape[1]:
    return False
  else:
    w, v = np.linalg.eig(m)
    return w,v


In [ ]:
m = np.array([[1, 2, 3],
              [2, 3, 4],
              [4, 5, 6]])

In [ ]:
compose(m)

(array([ 1.08309519e+01, -8.30951895e-01, -1.24701000e-16]),
 array([[ 0.34416959,  0.72770285,  0.40824829],
        [ 0.49532111,  0.27580256, -0.81649658],
        [ 0.79762415, -0.62799801,  0.40824829]]))

In [ ]:
def check_square(a):
    if a.shape[0]== a.shape[1]:
        return True
    else:
      return False
def decompose(a):
		# You are lucky here!
    if check_square(a):
        values,vectors=np.linalg.eig(a)
        return values,vectors
        
def combine(values,vectors):

		# This is not right comparision ... I didn't say they have to be equal values only equal lenghts
    # is it right now ?
    if values.shape[0] == vectors.shape[0]:
        return vectors@ np.diag(values)@np.linalg.inv(vectors)

In [ ]:
decompose(m)

(array([ 1.08309519e+01, -8.30951895e-01, -1.24701000e-16]),
 array([[ 0.34416959,  0.72770285,  0.40824829],
        [ 0.49532111,  0.27580256, -0.81649658],
        [ 0.79762415, -0.62799801,  0.40824829]]))

In [ ]:
combine(*decompose(m))
#* to unpack function and send it to another one 

array([[1., 2., 3.],
       [2., 3., 4.],
       [4., 5., 6.]])

In [30]:
rate = np.array([[.7,.15],[0.3,.85]])
population = np.array([[150],[150]])
simulation=0
for i in range(3):
		# simulaiton should be ?
     rate@population
    
    print(rate@population)

IndentationError: ignored

In [ ]:
A=np.array([[2,1],[1.5,4/3]])
B=np.array([[35],[35]])
np.linalg.inv(A).dot(B)

In [31]:
c=np.linalg.inv(rate).dot(population)
c

array([[190.90909091],
       [109.09090909]])

In [35]:
health=150
infected=150

for i in range(40):
  health=.7*health+.15*infected
  infected=.3* health+.85*infected
  print (health)
  print(infected)

127.5
165.75
114.1125
175.12124999999997
106.14693749999999
180.69714374999995
101.40742781249998
184.01480053124996
98.58741954843748
185.9888063160937
96.90951463132028
187.16333975807572
95.91116120563555
187.86218715605503
95.31714091735314
188.2780013578527
94.9636988458251
188.52541080792233
94.75340081326593
188.67261943071378
94.62827348389321
188.76020856127468
94.55382272291645
188.8123240939584
94.50952452013527
188.84333283590522
94.48316708948047
188.86178303736358
94.46748441824087
188.8727609072313
94.4581532288533
188.87929273980262
94.4526011711677
188.88317918018254
94.44929769684477
188.8854916122086
94.44733212962262
188.88686750926408
94.44616261712545
188.8876861680121
94.44546675718964
188.88817326996715
94.44505272052783
188.88846309563044
94.44480636871404
188.8886355419001
94.44465978938484
188.88873814743053
94.44457257468396
188.88879919772114
94.44452068193695
188.88883552264406
94.44448980575247
188.88885713597318
94.4444714344227
188.888869995904
94.44446

In [ ]:
health=np.array[[0.7,0.15],[0.3,0.85]]
rate=np.array[[150],[150]]
equ=0


In [36]:
x=np.array([2,1,1,0])
px=np.array([.25,.25,.25,.25])
np.sum(px*x)

1.0

In [38]:
x=np.array([0,0,1,0,0,0])
px=np.array([1/6,1/6,1/6,1/6,1/6,1/6])
np.sum(px*x)

0.16666666666666666

In [43]:
def check_mat(a):
    if a.shape[0]== a.shape[1]:
        return True
    else:
      return False

def stat(x,axis='col'):
  mat=np.array(x)
  check_mat(mat)
  if(axis=='col'):
    mean=np.mean(mat)
    variance=np.var(mat)
    standard=np.std(mat)
  elif(axis=='raw'):
      mean=np.mean(mat,axis='raw')
      variance=np.var(mat='raw')
      standard=np.std(mat='raw')
  else:
    return 'Error'
  return mean,variance,standard

In [ ]:
  stat()