In [2]:
import numpy as np

In [3]:
np.zeros(shape=(2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
s=np.array([[1,2,3],[4,5,6]])

In [5]:
s[:,1:]

array([[2, 3],
       [5, 6]])

In [6]:
x=np.arange(10)
x,x>5

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([False, False, False, False, False, False,  True,  True,  True,
         True]))

In [7]:
x[x>5]

array([6, 7, 8, 9])

In [8]:
x=np.array([[1,2,3,6,7,5,6],[4,5,6,10,2,4,6]])
x[x>4].reshape(2,-1)

array([[ 6,  7,  5,  6],
       [ 5,  6, 10,  6]])

In [9]:
arr=np.zeros(shape=(10,10,3))
arr


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
  

In [10]:
arr.reshape(10,-1)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [11]:
def reshapee(x,per:float):
  point=int(per*x.shape[0])
  point1=int(per*x.shape[1])
  return x[point:,point1:],x[:point,]


In [22]:
reshapee(t.reshape(-1,1),0.6)

NameError: ignored

In [ ]:
t=np.arange(11)
t.reshape((-1,1))

In [13]:
arr.shape[2]

3

In [14]:
a=np.array([[11,22,2],[33,34,99],[55,60,5]])

In [15]:
a

array([[11, 22,  2],
       [33, 34, 99],
       [55, 60,  5]])

In [16]:
a=a.reshape((a.shape[0],a.shape[1],1))
a,a.shape

(array([[[11],
         [22],
         [ 2]],
 
        [[33],
         [34],
         [99]],
 
        [[55],
         [60],
         [ 5]]]), (3, 3, 1))

In [17]:
def change(x,flag):
  if (flag=='col'):
    return (x.reshape(-1,2))
  else:
   
    return (x.reshape(2,-1))

In [18]:
change(b,'b')

NameError: ignored

In [23]:
ar=ar+ar

NameError: ignored

In [20]:
ar

NameError: ignored

In [ ]:
arr2=np.ones_like(ar)

In [21]:
arr2

NameError: ignored

In [ ]:
arr3=ar+arr2

In [ ]:
arr3=ar/ar
arr3

array([[1., 1.],
       [1., 1.]])

In [ ]:
ar=ar+.5
ar

array([[2.6, 4.6],
       [6.6, 8.6]])

In [ ]:
np.floor(ar)

array([[2., 4.],
       [6., 8.]])

In [ ]:
np.ceil(ar)

array([[3., 5.],
       [7., 9.]])

In [ ]:
np.round(ar)

array([[3., 5.],
       [7., 9.]])

In [ ]:
ar

array([[2.6, 4.6],
       [6.6, 8.6]])

In [ ]:
ar3=np.array([1,-1])

In [ ]:
ar3

array([ 2, -5])

In [ ]:
ar=np.array([[1,2],[3,4]])
ar.shape

(2, 2)

In [1]:
np.sum(ar,axis=0)

NameError: ignored

In [ ]:
ar=np.array([[1,2,3],[4,5,6]])
ar.shape

(2, 3)

In [ ]:
ar5=np.ones(shape=(3,4))

In [ ]:
np.dot(ar,ar5)

array([[ 6.,  6.,  6.,  6.],
       [15., 15., 15., 15.]])

In [ ]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [ ]:
x=np.identity(1)

In [ ]:
ar*x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
ar.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.trace(ar.dot(np.linalg.inv(ar)))

1.9999999999999996

In [ ]:
np.dot(np.linalg.inv(np.array([[1,1],[1,2]])),np.array([5,7]))

array([3., 2.])